# Build settings
#markdown: redcarpet
#highlighter: pygments
plugins:
  - jemoji
  - picture_tag
  
# Site settings
title: "Casually Cam"
description: > # this means to ignore newlines until "email:"
  Pudgy Girl in a Pudgy World

email: camille_p@verizon.net
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Camille Premo'
author: 'Camille Premo'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.base68.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/premoxoxo
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	instagram
    url:	https://www.instagram.com/premoxoxo/
    desc:	Follow me on Instagram
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

picture:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      source_lrg:
        media: "(min-width: 50em)"
        width: 1000
      source_med:
        media: "(min-width: 30em)"
        width: 700
      source_default:
        width: 600

# Glynn settings
ftp_host: 'base68.com'
ftp_dir: '/'
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: 'f009917a'     # default read from stdin

#gems
gems: [jekyll-paginate]


